engines:
  rubocop:
    enabled: true
  golint:
   	enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: false
  duplication:
  	enabled: true
    config:
    	languages:
      - ruby
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- 'app/assets/javascripts/bootstrap.js'
- 'app/assets/stylesheets/bootstrap.css'
