language: ruby
rvm:
 - 2.3.0
addons:
  postgresql: "9.4"
before_script:
  - cp config/database.yml.travis config/database.yml
  - openssl aes-256-cbc -K $encrypted_16325a7cddf2_key -iv $encrypted_16325a7cddf2_iv -in secrets.yml.enc -out secrets.yml -d
  - bundle exec rake db:create
  - bundle exec rake db:migrate
